homeassistant:
  name: Thuis
  latitude: !secret lattitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config/tmp/
    - /config/www/deurbel/
    - /config/www/video/
  internal_url: !secret internal_url
  external_url: !secret external_url
  media_dirs:
    camera: /config/www/video/
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/16
        - 127.0.0.1

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ip_ban_enabled: false
  login_attempts_threshold: 5

# Discover some devices automatically
discovery:

panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: !secret base_url_tasmo

logger:
  default: error
  logs:
    homeassistant.core: warn

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: !secret influx_db
  username: !secret influx_un
  password: !secret influx_pw
  max_retries: 3
  default_measurement: state

# Set up themes
frontend:
  themes: !include_dir_merge_named themes

folder_watcher:
- folder: /config/www/deurbel/foto

breaking_changes:

python_script:

magic_areas:

template:
  - trigger:
      - platform: time
        at: "23:59:59"
    sensor:
      - name: Max rain today
        state: "{{ states('sensor.eindhoven_rain_1d') }}"
        unit_of_measurement: "mm"
      - name: Rainchance today
        state: "{{ states('sensor.eindhoven_rainchance_1d') }}"
        unit_of_measurement: "%"
      - name: Max temp today
        state: "{{ states('sensor.eindhoven_temperature_1d') }}"
        unit_of_measurement: "°C"

google_assistant:
  project_id: amazing-limiter-212613
  service_account: !include My_Project-7788489780df.json

# notifier via google
notify:
  - platform: html5
    vapid_pub_key: !secret html_pub_key
    vapid_prv_key: !secret html_prv_key
    vapid_email: !secret html_email
    name: html5
  - platform: nfandroidtv
    name: bericht_woonkamertv
    host: 192.168.1.42
  - name: all_mobile
    platform: group
    services:
      - service: mobile_app_phone_erik
      - service: mobile_app_sm_g973f

# Text to speech
tts:
  - platform: google_cloud
    service_name: google_home_say
    key_file: amazing-limiter-212613-40c1df606f05.json
    language: nl-NL
    gender: female
    voice: nl-NL-Wavenet-D
    text_type: ssml
    #    encoding: linear16
    speed: 1
    pitch: -2.0
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: !secret tts_base_url
    language: "nl"
    service_name: google_translate_say

ifttt:
  key: !secret ifttt_key

tplink:
  discovery: false
  switch:
    - host: !secret switch_1
    - host: !secret switch_2
    - host: !secret switch_3

rest_command:
  genie_on:
    method: post
    url: !secret genie_on
    content_type: application/json
  genie_off:
    method: post
    url: !secret genie_off
    content_type: application/json
  genie_low:
    method: post
    url: !secret genie_low
    content_type: application/json
  genie_med:
    method: post
    url: !secret genie_med
    content_type: application/json
  genie_high:
    method: post
    url: !secret genie_high
    content_type: application/json
  genie_room_low:
    method: post
    url: !secret genie_room_low
    content_type: application/json
  genie_room_med:
    method: post
    url: !secret genie_room_med
    content_type: application/json
  genie_room_high:
    method: post
    url: !secret genie_room_high
    content_type: application/json

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  accounts:
    erik:
      sp_dc: !secret erik_sp_dc
      sp_key: !secret erik_sp_key
    nathalie:
      sp_dc: !secret nath_sp_dc
      sp_key: !secret nath_sp_key
    evie:
      sp_dc: !secret evie_sp_dc
      sp_key: !secret evie_sp_key
    jules:
      sp_dc: !secret jules_sp_dc
      sp_key: !secret jules_sp_key

camera:
  - platform: ffmpeg
    name: "Oprit"
    input: !secret cam_oprit
  - platform: ffmpeg
    name: "Woonkamer"
    input: !secret cam_woonkamer
  - platform: buienradar

stream:

shell_command:
  remove_video: find /config/www/video/* -mtime +3 -exec rm {} \;
  remove_foto_deurbel: find /config/www/deurbel/foto/* -mtime +2 -exec rm {} \;
  remove_video_deurbel: find /config/www/video/deurbel/* -mtime +2 -exec rm {} \;
  remove_woonkamer: find /config/www/video/woonkamer/* -mtime +3 -exec rm {} \;
  remove_oprit: find /config/www/video/oprit/* -mtime +3 -exec rm {} \;
  remove_g3: find /config/www/video/G3/* -mtime +3 -exec rm {} \;

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: false

home_connect:
  client_id: !secret homeconnect_client_id
  client_secret: !secret homeconnect_client_secret

weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily
  - platform: buienradar
    name: "Eindhoven"
    # Force 'Meetstation Eindhoven' to be used:
    latitude: 51.45
    longitude: 5.42
    forecast: true

airvisual:
  api_key: !secret airvisual_key

fan: !include includes/fan.yaml
media_player: !include includes/mediaplayers.yaml
group: !include includes/groups.yaml
automation split: !include_dir_merge_list automation
automation: !include automations.yaml
recorder: !include includes/recorder.yaml
script: !include_dir_merge_named scripts
sensor: !include includes/sensor.yaml
switch: !include includes/switch.yaml
light: !include includes/light.yaml
device_tracker: !include device_tracker.yaml
alarm_control_panel: !include resources/bwalarm/bwalarm.yaml
binary_sensor: !include includes/binary_sensor.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
input_select: !include includes/input_select.yaml
input_datetime: !include includes/input_date_time.yaml
input_text: !include includes/input_text.yaml
timer: !include includes/timer.yaml
utility_meter: !include includes/utilitymeter.yaml