- platform: google_maps
  username: !secret hass_maps_user

#- platform: netgear
#  host: !secret router_url
#  port: "80"
#  password: !secret short_password
#  new_device_defaults:
#    track_new_devices: false

#- platform: huesensor

- platform: ping
  hosts:
    erik: !secret erik_phone
    nathalie: !secret nathalie_phone

# - platform: bluetooth_le_tracker
#   track_new_devices: true