sound_siren_in_doorbell_mode:
  alias: Sound Siren In Doorbell Mode
  sequence:
  - service: zwave_js.set_config_parameter
    target:
      entity_id: switch.siren_alarm_current_value
    data:
      parameter: 7
      value: 2
  - service: switch.turn_on
    entity_id: switch.siren_alarm_current_value
sound_siren_in_alarm_mode:
  alias: Sound Siren In Alarm Mode
  sequence:
  - service: zwave_js.set_config_parameter
    target:
      entity_id: switch.siren_alarm_current_value
    data:
      parameter: 7
      value: 1