send_command:
  description: Send miio command.
  fields:
    entity_id:
      description: ID of the entity.
      example: "light.yeelight_living_e92c"
      required: true
      selector:
        entity:
          integration: xiaomi_miot
    method:
      description: Method of the command.
      example: set_power
      required: true
      selector:
        text:
    params:
      description: Params for the method.
      example: ['on']
      required: true
      selector:
        object:

get_properties:
  description: Get miot properties.
  fields:
    entity_id:
      description: ID of the entity.
      example: "climate.xiaomi_mc5_374e"
      required: true
      selector:
        entity:
          integration: xiaomi_miot
    mapping:
      description: Mapping for properties.
      example: "{'power': {'siid': 2, 'piid': 1}}"
      required: true
      selector:
        object:
    throw:
      description: Throw properties.
      example: true
      selector:
        boolean:

set_property:
  description: Set miot property.
  fields:
    entity_id:
      description: ID of the entity.
      example: "climate.xiaomi_mc5_374e"
      required: true
      selector:
        entity:
          integration: xiaomi_miot
    field:
      description: Field of property.
      example: "air_conditioner.on"
      required: true
      selector:
        text:
    value:
      description: Value of property.
      example: true
      required: true
      selector:
        object:

set_miot_property:
  description: Set miot property by siid/piid.
  fields:
    entity_id:
      description: ID of the entity.
      example: "climate.xiaomi_mc5_374e"
      required: true
      selector:
        entity:
          integration: xiaomi_miot
    siid:
      description: Miot service ID.
      example: 2
      required: true
      selector:
        number:
          min: 1
          max: 9999
          mode: box
    piid:
      description: Miot property ID.
      example: 1
      required: true
      selector:
        number:
          min: 1
          max: 9999
          mode: box
    value:
      description: Miot property value.
      example: true
      required: true
      selector:
        object:

call_action:
  description: Call miot action.
  fields:
    entity_id:
      description: ID of the entity.
      example: "media_player.xiaoai_x08c"
      required: true
      selector:
        entity:
          integration: xiaomi_miot
    siid:
      description: Miot service ID.
      example: 3
      required: true
      selector:
        number:
          min: 1
          max: 9999
          mode: box
    aiid:
      description: Miot action ID.
      example: 5
      required: true
      selector:
        number:
          min: 1
          max: 9999
          mode: box
    params:
      description: Miot action params.
      example: "['Turn on light', 1]"
      selector:
        object:
    throw:
      description: Throw result.
      example: false
      selector:
        boolean:

intelligent_speaker:
  description: Play text / Execute text directive.
  fields:
    entity_id:
      description: ID of the entity.
      example: "media_player.xiaoai_x08c"
      required: true
      selector:
        entity:
          integration: xiaomi_miot
          domain: media_player
    text:
      description: Text content.
      example: "Turn on light"
      required: true
      selector:
        text:
    execute:
      description: Execute text directive.
      example: true
      selector:
        boolean:
    silent:
      description: Silent execution.
      example: false
      selector:
        boolean:

get_device_data:
  description: Get xiaomi device data from cloud.
  fields:
    entity_id:
      description: ID of the entity.
      example: "sensor.xiaomi_lock"
      required: true
      selector:
        entity:
          integration: xiaomi_miot
    type:
      description: Data type.
      example: prop
      selector:
        select:
          options:
            - prop
            - event
    key:
      description: Data key.
      example: power
      required: true
      selector:
        text:
    time_start:
      example: 0
      selector:
        number:
          min: 0
          max: 9999999999
          mode: box
    time_end:
      example: 0
      selector:
        number:
          min: 0
          max: 9999999999
          mode: box
    limit:
      example: 10
      selector:
        number:
          min: 1
          max: 2000
          mode: box
    group:
      example: raw
      selector:
        select:
          options:
            - raw
            - hour
            - day
            - week
            - month

get_token:
  description: Get xiaomi device token.
  fields:
    entity_id:
      description: ID of the entity.
      example: "climate.xiaomi_mc5_374e"
      required: true
      selector:
        entity:
          integration: xiaomi_miot
    name:
      description: Device name.
      selector:
        text:

get_bindkey:
  description: Get bindkey for ble device from cloud.
  fields:
    entity_id:
      description: ID of the entity.
      example: "sensor.lywsd03mmc"
      required: true
      selector:
        entity:
          integration: xiaomi_miot
    name:
      description: Xiaomi device ID.
      selector:
        text:

request_xiaomi_api:
  description: Request xiaomi cloud api.
  fields:
    entity_id:
      description: ID of the entity.
      example: "sensor.xiaomi_device"
      required: true
      selector:
        entity:
          integration: xiaomi_miot
    api:
      example: "/home/device_list"
      selector:
        text:
    params:
      example: "{'getVirtualModel':true}"
      selector:
        object:
