#########################
####### Thema ###########
#########################
- id: 'themestartup'
  alias: 'Custom Theme bij Startup'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: 'Google Light Theme'
- id: 'changetheme'
  alias: 'System - Change Current Theme'
  trigger:
    - platform: state
      entity_id: input_select.themes
  action:
    - service: frontend.set_theme
      data_template:
        name: "{{states('input_select.themes')}}"

##################################################################
#       Goedemorgen Werkdagen                                    #
##################################################################
- alias: Google Home - Goedemorgen Werkdagen
  trigger:
    - platform: state  
      entity_id: binary_sensor.nas_pd02z_battery_powered_pir_sensor_v2_sensor_4
      from: 'off'
      to: 'on'
    - entity_id: sensor.woonkamer_remote
      platform: state
      to: 1_click_up
    - platform: state
      entity_id: binary_sensor.motion_schuifpui
      from: 'off'
      to: 'on'
    - entity_id: binary_sensor.motion_sensor_woonkamer
      from: 'off'
      platform: state
      to: 'on'
  condition:
    - condition: time
      after: '06:00:00'
      before: '07:30:00'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: state
      entity_id: input_boolean.ochtendgebed
      state: 'off'
  action:
    - service: bluesound.unjoin
      entity_id: media_player.keuken_speaker
    - delay: 00:05:00
    - service: script.turn_on
      entity_id: script.weerscript
    - delay: 00:00:30
    - service: script.turn_on
      entity_id: script.afvalscript
    - delay: 00:00:30
    - service: script.turn_on
      entity_id: script.agendascript
    - delay: 00:00:30
    - service: script.turn_on
      entity_id: script.nieuwsscript
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.ochtendgebed
##############################################
########## Home mini's ####################
#######################################
- id: '1602073411856'
  alias: Houd de home minis wakker
  description: ''
  trigger:
  - platform: time_pattern
    minutes: "/2"
  condition: []
  action:
    - service: media_player.play_media
      data_template:
        media_content_id: https://silverentand.duckdns.org/local/1sec.mp3
        media_content_type: music
        entity_id: >-
          media_player.dummy
          {% if states("media_player.werkkamer_mini") != "playing" %}, media_player.werkkamer_mini{% endif %}
          {% if states("media_player.ouderslaapkamer_mini") != "playing" %}, media_player.ouderslaapkamer_mini{% endif %}
          {% if states("media_player.home_mini_woonkamer") != "playing" %}, media_player.home_mini_woonkamer{% endif %}
- alias: Mediaspelers uit door nacht
  trigger:
    - platform: state
      entity_id: input_boolean.nachtstand
      to: 'on'
    - platform: state
      entity_id: input_boolean.vakantiestand
      to: 'on'
    - platform: state
      entity_id: input_boolean.notify_home
      to: 'on'
  condition: []
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.65oled854_12
        - input_boolean.android_tv_woonkamer
        - input_boolean.eetkamer_speakers
        - input_boolean.keuken_hub
        - input_boolean.keuken_speaker
        - input_boolean.ouderslaapkamer_mini
        - input_boolean.werkkamer_mini
        - input_boolean.ouderslaapkamer
        - input_boolean.eetkamer
        - input_boolean.woonkamer_ultra
- alias: Mediaspelers uit door nacht
  trigger:
    - platform: state
      entity_id: input_boolean.nachtstand
      to: 'off'
    - platform: state
      entity_id: input_boolean.vakantiestand
      to: 'off'
    - platform: state
      entity_id: input_boolean.notify_home
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.vakantiestand
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: group.all_persons
        state: home
      - condition: state
        entity_id: person.erik
        state: home
      - condition: state
        entity_id: person.nathalie
        state: home
  action:
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.home_mini_woonkamer
        - input_boolean.ouderslaapkamer_mini
        - input_boolean.werkkamer_mini
############################
###### update Hassio #######
############################
- alias: update message hassio
  trigger:
    platform: state
    entity_id: binary_sensor.updater
    from: 'off'
    to: 'on'
  action:
    service: notify.mobile_app_phone_erik
    data:
      message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is beschikbaar."
      title: 'Home Assistant Update'
      data:
        sticky: 'false'   
        color: 'green'
        persistent: true           # set to persistent
        clickAction: /hassio/dashboard    # navigate user to the lovelace alarm view
        icon: 'mdi:alarm-light'
        group: update
        tag: update
- alias: Create a notification when somethig is added to HACS
  trigger:
    platform: event
    event_type: hacs/repository
    event_data:
      action: registration
  condition:
    condition: template
    value_template: "{{ trigger.event.data.repository is defined }}"
  action:
    service: persistent_notification.create
    data_template:
      title: Nieuw item in HACS
      message: >-
        {% set repo = trigger.event.data.repository %}
        {% set id = trigger.event.data.repository_id %}
        [{{ repo }}](/hacs/repository/{{ id }})
        is net toegevoegd aan HACS.
############################
########### P2000 ##########
############################
- alias: 'P2000 Bericht'
  trigger:
    platform: state
    entity_id: sensor.veldhoven_e_o
  action:
    - service: notify.mobile_app_phone_erik
      data_template:
        title: "P2000 Bericht"
        message: >
          {{ states('sensor.veldhoven_e_o') + state_attr('sensor.veldhoven_e_o', 'capcodes') }}
        data:
          url: "https://www.google.com/maps/search/?api=1&query={{ state_attr('sensor.veldhoven_e_o', 'latitude') }},{{ state_attr('sensor.veldhoven_e_o', 'longitude') }}"
##############################
######## Files opschonen #####
##############################
- alias: Oude video-files opschonen
  trigger:
    platform: time
    at: '03:00:00'
  condition: []
  action:
    service: shell_command.remove_video
###########################
##### DB Cleanup ##########
###########################
- alias: Purge Database
  initial_state: True
  trigger:
    platform: time
    at: '03:00:00'
  action:
    service: recorder.purge
    data:
      keep_days: 7
      repack: true
###########################
######## Test ruimte #####
###########################
- alias: testknop actie
  trigger:
    - platform: state
      entity_id: input_boolean.test
      to: 'on'
  action:
  - service: script.turn_on
    entity_id: script.mediaplayer_say
    data:
      variables:
        player2: 'media_player.werkkamer_mini'
        google_say: 'als je dit hoort werkt het'