#########################
####### Thema ###########
#########################
- id: 'themestartup'
  alias: 'Custom Theme bij Startup'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: 'Google Light Theme'
- id: 'changetheme'
  alias: 'System - Change Current Theme'
  trigger:
    - platform: state
      entity_id: input_select.themes
  action:
    - service: frontend.set_theme
      data_template:
        name: "{{states('input_select.themes')}}"

################################
######## Nachtstand ############
################################
- id: "1560969346149"
  alias: Nachtstand activeren
  trigger:
    - entity_id: binary_sensor.nachtmode_aan
      platform: state
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: group.all_persons
          state: "home"
        - condition: state
          entity_id: person.erik
          state: "home"
        - condition: state
          entity_id: person.nathalie
          state: "home"
        - condition: state
          entity_id: input_boolean.notify_home
          state: "on"
        - condition: state
          entity_id: input_boolean.vakantiestand
          state: "off"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.nachtstand
- id: "1560969455159"
  alias: Nachtstand uit
  trigger:
    - entity_id: binary_sensor.nachtmode_aan
      platform: state
      to: "off"
  action:
    - data:
        entity_id: input_boolean.nachtstand
      service: input_boolean.turn_off
    - data:
        entity_id: input_boolean.ochtendgebed
      service: input_boolean.turn_off
    - data:
        entity_id: input_boolean.ochtendmuziek
      service: input_boolean.turn_off
- alias: Acties door nachtschakelaar uit
  trigger:
    - entity_id: input_boolean.nachtstand
      platform: state
      to: "off"
  condition:
    - condition: state
      entity_id: input_boolean.vakantiestand
      state: "off"
  action:
    - service: frontend.set_theme
      data:
        name: "Google Light Theme"
    - service: script.turn_on
      data_template:
        entity_id:
          "{% if is_state('binary_sensor.low_lux_input_eetkamer', 'on' ) and is_state('group.all_persons',\
          \ 'home') and is_state('binary_sensor.workday', 'on' ) %}\n  script.daglicht_aan\n\
          {% else %}\n  script.noop\n{% endif %}"
    - service: input_boolean.turn_off
      data_template:
        entity_id:
          "{% if is_state('input_boolean.notify_home', 'on' ) or is_state('group.all_persons',\
          \ 'home') %}\n  input_boolean.camera_switch\n{% endif %}"
    - service: light.turn_on
      data_template:
        entity_id:
          "{% if is_state('binary_sensor.low_lux_input_eetkamer', 'on' ) and is_state('group.all_persons',\
          \ 'home') %}\n  light.tuinverlichting\n{% endif %}"
  id: "fd0c63b0a0a94672a6da52a8c5b03385"
- alias: Acties door nachtschakelaar aan
  trigger:
    - entity_id: input_boolean.nachtstand
      platform: state
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.verlichting_steady_eetkamer
      state: "off"
    - condition: state
      entity_id: input_boolean.verlichting_steady_woonkamer
      state: "off"
  action:
    - service: script.turn_on
      data:
        entity_id: script.nachtlicht_uit
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.camera_switch
    - service: light.turn_off
      data:
        entity_id: light.liefde
    - service: light.turn_off
      data:
        entity_id: light.tuinverlichting
    - service: light.turn_off
      data:
        entity_id:
          - light.spotjes_werkkamer
          - light.spotjes_speelkamer
    - service: frontend.set_theme
      data:
        name: "Google Dark Theme"
  id: 2d994bb1880c4cb79f5f0bfe51f65c21

- id: "kinderbedtijd23452345"
  alias: Kinderbedtijd activeren
  trigger:
    - entity_id: binary_sensor.kinderbedtijd
      platform: state
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: group.all_persons
          state: "home"
        - condition: state
          entity_id: person.erik
          state: "home"
        - condition: state
          entity_id: person.nathalie
          state: "home"
        - condition: state
          entity_id: input_boolean.notify_home
          state: "on"
        - condition: state
          entity_id: input_boolean.vakantiestand
          state: "off"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.kinderbedtijd
##########################
###### Vakantiestand #####
##########################
- alias: Scene vakantie
  trigger:
    - platform: state
      entity_id: binary_sensor.low_lux_input_woonkamer
      to: "on"
    - platform: time
      at: "22:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.vakantiestand
      state: "on"
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: binary_sensor.low_lux_input_woonkamer
              state: "on"
            - condition: time
              before: "22:00:00"
        - condition: template
          value_template: '{{ trigger.platform == "time" }}'
  action:
    - delay: '{% if trigger.platform == "state" %}00:00:10{% else %}0{{ (range(0,1)|random|int) }}:{{ (range(10, 59)|random|int) }}:{{ (range(10, 59)|random|int) }}{% endif %}'
    - service: 'light.turn_{{ trigger.platform|replace("state", "on")|replace("time", "off") }}'
      entity_id: light.beneden
    - service: persistent_notification.create
      data_template:
        message: 'lichten {% if trigger.to_state.state == "on" %}aan{% else %}uit{%endif %}'
        title: Verlichting in de vakantie
    - service: notify.html5_home_assistant
      data_template:
        message: 'lichten {% if trigger.to_state.state == "on" %}aan{% else %}uit{%endif %}'
        title: Verlichting in de vakantie

##################################################################
#       Goedemorgen Werkdagen                                    #
##################################################################
- alias: Google Home - Goedemorgen Werkdagen
  trigger:
    - platform: state  
      entity_id: binary_sensor.pir_motion_sensor_eetkamer
      from: 'off'
      to: 'on'
    - entity_id: sensor.woonkamer_remote
      platform: state
      to: 1_click_up
    - entity_id: binary_sensor.motion_sensor_woonkamer
      from: 'off'
      platform: state
      to: 'on'
  condition:
    - condition: time
      after: '06:00:00'
      before: '07:30:00'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: state
      entity_id: input_boolean.ochtendgebed
      state: 'off'
  action:
    - service: bluesound.unjoin
      entity_id: media_player.keuken_speaker
    - delay: 00:05:00
    - service: script.turn_on
      entity_id: script.weerscript
    - delay: 00:00:30
    - service: script.turn_on
      entity_id: script.weeralarmscript
    - delay: 00:00:20
    - service: script.turn_on
      entity_id: script.afvalscript
    - delay: 00:00:30
    - service: script.turn_on
      entity_id: script.agendascript
    - delay: 00:00:30
    - service: script.turn_on
      entity_id: script.nieuwsscript
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.ochtendgebed
##############################################
########## Home mini's ####################
#######################################
- id: '1602073411856'
  alias: Houd de home minis wakker
  description: ''
  trigger:
  - platform: time_pattern
    minutes: "/2"
  condition: []
  action:
    - service: media_player.play_media
      data_template:
        media_content_id: https://silverentand.duckdns.org/local/1sec.mp3
        media_content_type: music
        entity_id: >-
          media_player.dummy
          {% if states("media_player.werkkamer_mini") != "playing" %}, media_player.werkkamer_mini{% endif %}
          {% if states("media_player.yogakamer_mini") != "playing" %}, media_player.yogakamer_mini{% endif %}
          {% if states("media_player.home_mini_woonkamer") != "playing" %}, media_player.home_mini_woonkamer{% endif %}
- alias: Mediaspelers uit door nacht
  trigger:
    - platform: state
      entity_id: input_boolean.nachtstand
      to: 'on'
    - platform: state
      entity_id: input_boolean.kinderbedtijd
      to: 'on'
    - platform: state
      entity_id: input_boolean.vakantiestand
      to: 'on'
    - platform: state
      entity_id: input_boolean.notify_home
      to: 'on'
  condition: []
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.65oled854_12
        - input_boolean.android_tv_woonkamer
        - input_boolean.eetkamer_speakers
        - input_boolean.keuken_hub
        - input_boolean.keuken_speaker
        - input_boolean.yogakamer_mini
        - input_boolean.werkkamer_mini
        - input_boolean.ouderslaapkamer
        - input_boolean.eetkamer
        - input_boolean.woonkamer_ultra
- alias: Mediaspelers aan na nacht
  trigger:
    - platform: state
      entity_id: input_boolean.nachtstand
      to: 'off'
    - platform: state
      entity_id: input_boolean.vakantiestand
      to: 'off'
    - platform: state
      entity_id: input_boolean.notify_home
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.vakantiestand
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: group.all_persons
        state: home
      - condition: state
        entity_id: person.erik
        state: home
      - condition: state
        entity_id: person.nathalie
        state: home
  action:
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.home_mini_woonkamer
        - input_boolean.yogakamer_mini
        - input_boolean.werkkamer_mini
        - input_boolean.keuken_hub
############################
##### Berichten via TTS ####
############################
- alias: Tekst voor lovelace
  description: Teskt die gebruikt moet worden in Lovelace
  trigger:
  - entity_id: input_text.tts_bericht
    platform: state
  condition: []
  action:
  - service: script.turn_on
    entity_id: script.mediaplayer_say
    data:
      variables:
        player2: |
          {% if is_state("input_select.afspeelmedium", "Woonkamer (Chromecast)") %} media_player.woonkamer_ultra
          {% elif is_state("input_select.afspeelmedium", "Woonkamer (Home Mini)") %} media_player.home_mini_woonkamer
          {% elif is_state("input_select.afspeelmedium", "Werkkamer") %} media_player.werkkamer_mini
          {% elif is_state("input_select.afspeelmedium", "Yogakamer") %} media_player.yogakamer_mini        
          {% elif is_state("input_select.afspeelmedium", "Eetkamer") %} media_player.eetkamer
          {% elif is_state("input_select.afspeelmedium", "Keukenspeaker") %} media_player.keuken_speaker_2
          {% elif is_state("input_select.afspeelmedium", "Nest Hub Keuken") %} media_player.keuken_hub
          {% elif is_state("input_select.afspeelmedium", "Zolder") %} media_player.werkkamer_mini, media_player.yogakamer_mini
          {% endif %}
        google_say: "{{ states('input_text.tts_bericht') }}"
  - service: input_text.set_value
    entity_id: input_text.tts_bericht
    data:
      value: ""

############################
###### update Hassio #######
############################
- alias: update message hassio
  trigger:
    platform: state
    entity_id: binary_sensor.updater
    from: 'off'
    to: 'on'
  action:
    service: notify.mobile_app_phone_erik
    data:
      message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is beschikbaar."
      title: 'Home Assistant Update'
      data:
        sticky: 'false'   
        color: 'green'
        persistent: true           # set to persistent
        clickAction: /hassio/dashboard    # navigate user to the lovelace alarm view
        icon: 'mdi:alarm-light'
        group: update
        tag: update
- alias: Create a notification when somethig is added to HACS
  trigger:
    platform: event
    event_type: hacs/repository
    event_data:
      action: registration
  condition:
    condition: template
    value_template: "{{ trigger.event.data.repository is defined }}"
  action:
    service: persistent_notification.create
    data_template:
      title: Nieuw item in HACS
      message: >-
        {% set repo = trigger.event.data.repository %}
        {% set id = trigger.event.data.repository_id %}
        [{{ repo }}](/hacs/repository/{{ id }})
        is net toegevoegd aan HACS.
############################
########### P2000 ##########
############################
- alias: 'P2000 Bericht'
  trigger:
    platform: state
    entity_id: sensor.veldhoven_e_o
  action:
    - service: notify.mobile_app_phone_erik
      data_template:
        title: "P2000 Bericht"
        message: >
          {{ states('sensor.veldhoven_e_o') + state_attr('sensor.veldhoven_e_o', 'capcodes') }}
        data:
          url: "https://www.google.com/maps/search/?api=1&query={{ state_attr('sensor.veldhoven_e_o', 'latitude') }},{{ state_attr('sensor.veldhoven_e_o', 'longitude') }}"
##############################
######## Files opschonen #####
##############################
- alias: Oude video-files opschonen
  trigger:
    platform: time
    at: '03:00:00'
  condition: []
  action:
    - service: shell_command.remove_video
    - service: shell_command.remove_foto_deurbel
    - service: shell_command.remove_video_deurbel
    - service: shell_command.remove_oprit
    - service: shell_command.remove_woonkamer
    - service: shell_command.remove_g3
###########################
##### DB Cleanup ##########
###########################
- alias: Purge Database
  initial_state: True
  trigger:
    platform: time
    at: '03:00:00'
  action:
    service: recorder.purge
    data:
      keep_days: 7
      repack: true

###########################
######## Test ruimte #####
###########################
- alias: testknop actie
  trigger:
    - platform: state
      entity_id: input_boolean.test
      to: 'on'
  action:
  - service: script.turn_on
    entity_id: script.mediaplayer_say
    data:
      variables:
        player2: 'media_player.werkkamer_mini, media_player.yogakamer_mini'
        google_say: 'Er staat iemand aan de deur!'