- alias: Update OpenUV elke 30 minuten overdag
  trigger:
    platform: time_pattern
    minutes: '/30'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunrise
      - condition: sun
        before: sunset
  action:
    service: openuv.update_data