- alias: zonnescherm uitrollen
  id: 1234zonuitrol
  trigger:
    - platform: time_pattern
      minutes: "/5"
  condition:
    - condition: state
      entity_id: group.all_persons
      state: "home"
    - condition: state
      entity_id: input_boolean.vakantiestand
      state: "off"
    - condition: state
      entity_id: input_boolean.zonwering_open
      state: "on"
    - condition: template
      value_template: >-
        {{ states('sensor.bijkeuken')|int > 220 }}
    - condition: state
      entity_id: binary_sensor.pv_system_input
      state: "on"
    - condition: state
      entity_id: binary_sensor.azimuth_input
      state: "on"
    - condition: state
      entity_id: binary_sensor.zonhoek_low_input
      state: "off"
    - condition: numeric_state
      entity_id: sensor.eindhoven_wind_gust
      below: 40
    - condition: template
      value_template: >-
        {% if states('sensor.buienalarm_next_rain_forecast') != "unknown" %}
          {{ states('sensor.buienalarm_next_rain_forecast')|int < 0 or states('sensor.buienalarm_next_rain_forecast')|int > 15 }}
        {% else %}
          {{ states('sensor.buienalarm_precipitation')|int == 0 }}
        {% endif %}
    - condition: state
      entity_id: binary_sensor.low_irradiance_input
      state: "on"
    - condition: state
      entity_id: binary_sensor.lichtwaarde_input
      state: "on"
    - condition: numeric_state
      entity_id: sensor.temperature_eetkamer
      above: 19
    - condition: template
      value_template: "{{ now().month > 2 }}"
    - condition: template
      value_template: "{{ now().month < 10 }}"
    - condition: state
      entity_id: input_boolean.disable_automatic_sunscreens
      state: "on"
    - condition: state
      entity_id: input_boolean.vakantiestand
      state: "off"
  action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.neo_coolcam_roller_shutter_curtain_switch
        position: 0
    - delay:
        seconds: 10
    - service: input_boolean.turn_off
      entity_id: input_boolean.zonwering_open
    - service: notify.html5
      data:
        message: "Het zonnescherm is geopend"
        title: zonnescherm
    - service: notify.all_mobile
      data:
        message: "Het zonnescherm is geopend"
        title: zonnescherm
    - delay:
        minutes: 5
    - service: html5.dismiss
- alias: zonnescherm inrollen
  id: 1234zoninrol
  trigger:
    - platform: state
      entity_id: binary_sensor.azimuth_input
      to: "off"
    - platform: state
      entity_id: binary_sensor.zonhoek_low_input
      to: "on"
    - platform: numeric_state
      entity_id: sensor.solaredge_ac_power
      below: 1000
      for:
        minutes: 10
    - platform: state
      entity_id: sun.sun
      to: "below_horizon"
    - platform: state
      entity_id: binary_sensor.lichtwaarde_input
      to: "off"
      for:
        minutes: 10
#    - platform: state
#      entity_id: binary_sensor.low_irradiance_input
#      to: "off"
#      for:
#        minutes: 30
    - platform: numeric_state
      entity_id: sensor.eindhoven_wind_gust
      above: 40
    - platform: numeric_state
      entity_id: sensor.buienalarm_next_rain_forecast
      above: 0
      below: 15
  condition:
    - condition: state
      entity_id: input_boolean.zonwering_open
      state: "off"
    - condition: state
      entity_id: input_boolean.disable_automatic_sunscreens
      state: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.zonwering_open
    - service: media_player.volume_set
      data:
        entity_id: media_player.eetkamer_speakers
        volume_level: 0.5
    - service: tts.google_translate_say
      entity_id: media_player.eetkamer_speakers
      data_template:
        message: "Het zonnescherm gaat sluiten. Reden: {{ state_attr(trigger.entity_id, 'friendly_name') }}"
        language: "nl"
        cache: false
    - service: notify.html5
      data:
        message: "Het zonnescherm is gesloten"
        title: zonnescherm
    - service: notify.all_mobile
      data_template:
        message: "Het zonnescherm gaat sluiten, reden: {{ state_attr(trigger.entity_id, 'friendly_name') }}"
        title: zonnescherm
    - service: media_player.volume_set
      data:
        entity_id: media_player.eetkamer_speakers
        volume_level: 0.2
    - delay:
        seconds: 10
    - service: cover.set_cover_position
      data:
        entity_id: cover.neo_coolcam_roller_shutter_curtain_switch
        position: 100
    - delay:
        minutes: 10
    - service: html5.dismiss
- alias: schakelaar om bij uitklappen zonnescherm
  trigger:
    - platform: state
      entity_id: cover.neo_coolcam_roller_shutter_curtain_switch
      to: "closed"
  condition:
    - condition: state
      entity_id: input_boolean.zonwering_open
      state: "on"
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.zonwering_open
- alias: schakelaar om bij inklappen zonnescherm
  trigger:
    - platform: state
      entity_id: cover.neo_coolcam_roller_shutter_curtain_switch
      to: "open"
  condition:
    - condition: state
      entity_id: input_boolean.zonwering_open
      state: "off"
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.zonwering_open
