- platform: broadlink
  host: 192.168.1.6
  mac: 'B4:43:0D:CB:EB:CD'
  type:  sp3
  friendly_name: "Tuinverlichting"

- platform: broadlink
  host: 192.168.1.7
  mac: '34:EA:34:9D:36:76'
  type:  sp3
  friendly_name: "Koffie"

- platform: broadlink
  host: 192.168.1.9
  mac: '34:EA:34:9D:1C:50'
  type:  sp3
  friendly_name: "Haard"

- platform: template
  switches:
    genie:
      friendly_name: "Genie"
      value_template: "{{ is_state('binary_sensor.genie_status', 'on') }}"
      turn_on:
        service: rest_command.genie_on
      turn_off:
        service: rest_command.genie_off
        
- platform: philips_ambilight+hue
  name: Ambilight+Hue
  host: !secret tv_woonkamer
  username: !secret tv_username
  password: !secret tv_password
  scan_interval: 5