- platform: broadlink
  mac: B4:43:0D:CB:EB:CD
#  friendly_name: "Tuinverlichting"

- platform: broadlink
  mac: 34:EA:34:9D:36:76
#  friendly_name: "Koffie"

- platform: broadlink
  mac: 34:EA:34:9D:1C:50
#  friendly_name: "Haard"

- platform: philips_ambilight+hue
  name: Ambilight+Hue
  secured_transport: true
  api_version: 6
  host: !secret tv_woonkamer
  username: !secret tv_username
  password: !secret tv_password
# #  id: 2131230783
  scan_interval: 5

- platform: template
  switches:
    genie:
      friendly_name: "Genie"
      value_template: "{{ is_state('binary_sensor.genie_status', 'on') }}"
      turn_on:
        service: rest_command.genie_on
      turn_off:
        service: rest_command.genie_off

- platform: wake_on_lan
  name: TV woonkamer aanzetten
  mac: !secret tv_mac
  broadcast_address: !secret tv_woonkamer